#pragma once
// pf_rank.hpp - preflop class strength: PF_PCT[c] = share of all 1,326 combos whose class is at least as
// strong as class c, by mean equity against a random hand (solvers/eq169.bin, combo-weighted).
// Generated by the snippet in analysis/postmortem.py's history (see bot/README.md); class index as in pf_tables.hpp.
namespace pf {
const unsigned char PF_PCT100[169] = {44, 100, 99, 97, 98, 96, 91, 86, 77, 69, 59, 48, 33, 95, 33, 95, 93, 94, 92, 90, 82, 75, 65, 54, 45, 29, 92, 86, 20, 88, 89, 87, 85, 80, 71, 63, 53, 41, 26, 89, 83, 78, 12, 83, 81, 78, 74, 70, 60, 49, 39, 25, 89, 84, 79, 73, 7, 76, 72, 68, 63, 57, 46, 35, 24, 87, 81, 76, 70, 64, 4, 66, 61, 57, 51, 42, 32, 18, 81, 79, 73, 67, 62, 56, 3, 55, 51, 44, 37, 28, 16, 75, 71, 70, 64, 58, 52, 47, 3, 43, 38, 30, 21, 14, 67, 64, 60, 59, 53, 47, 40, 34, 2, 31, 23, 15, 10, 58, 54, 52, 50, 47, 40, 34, 28, 22, 2, 19, 13, 8, 48, 45, 41, 39, 37, 34, 27, 22, 17, 14, 1, 11, 6, 38, 36, 33, 28, 25, 23, 20, 14, 10, 9, 8, 1, 5, 25, 20, 17, 17, 17, 13, 10, 9, 7, 5, 4, 3, 0};
}  // namespace pf
